# Generated by Django 2.1.1 on 2018-11-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180923_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='The project description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='The project content'),
        ),
    ]
