# Generated by Django 2.1.1 on 2018-11-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181120_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description_img_url',
            field=models.TextField(default='https://gw.alipayobjects.com/zos/rmsportal/mqaQswcyDLcXyDKnZfES.png'),
        ),
    ]
